### ISSUE TITLE
`onComplete(root())` callback sometimes not invoked when defined in several models

### ISSUE THREAD

**Issue by kateabr** [instancio/instancio#1159]
**Describe the bug**
When plugging several models with `onComplete(root())` hook, the `onComplete()` callback is is only performed for the model that was added first.

**Expected result**
`onComplete()` is performed for all models regardless of the import order

**Actual result**
`onComplete()` only performed for the first model

**Additional information**
May not be an actual bug, but iirc this behavior is not described in the docs

**Link to a minimal sample project reproducing the issue or runnable sample code**
https://github.com/kateabr/instancio_on_complete_example
Please run [OnCompleteTest](https://github.com/kateabr/instancio_on_complete_example/blob/master/src/test/java/com/example/demo/OnCompleteTest.java) for a reproducible example.

- Java version: 17
- Instancio version: 5.0.1

**Comment by armandino** [comment]
@kateabr thanks for raising this issue and the sample project! From what I can tell, it is working as expected. Having said that, it's a pretty complicated example, so I don't fully understand all the pieces and maybe I misunderstood something.

When the models get combined, if there are multiple _equal_ selectors, then the last selector wins. A simplified example would be this:

```java
@Test
void callbacks() {
    record Foo(String value) {}

    Instancio.of(Foo.class)
            .onComplete(root(), value -> System.out.println("Callback 1: " + value))
            .onComplete(root(), value -> System.out.println("Callback 2: " + value)) // overwrites the first onComplete()
            .create();

// Sample output:
// Callback 2: Foo[value=ZKWYN]
}
```

This behaviour applies to regular selectors (e.g. `Select.field()` and `Select.all(Class)`) as well as the `root()` selector.

You might be able to workaround this by replacing `root`() with an  equivalent predicate selector:

```java
Instancio.of(Foo.class)
        .onComplete(types().atDepth(0), value -> System.out.println("Callback 1: " + value))
        .onComplete(types().atDepth(0), value -> System.out.println("Callback 2: " + value))
        .create();

// Sample output:
// Callback 2: Foo[value=FHXVXL]
// Callback 1: Foo[value=FHXVXL]
```

In this case, both callbacks are called because predicate selectors can't overwrite each other (because there's no `equals()` for predicates).

I'm not sure if this addresses your question since your example is much more complicated. If you could simplify it to the absolute minimum, I could look into further.

**Comment by kateabr** [comment]
Thank you for your answer!
I suspected they could be overwriting each other, but then, as you said, one would expect the last selector to win, not the first one?

I tried replacing `root()` with `types().of(X)` and `types().of(X).atDepth(0)` and it does work, but in my particular case (as in the first version of my example) the entities have multiple cyclic references, so the callback ends up being invoked twice.

I've simplified my example, so please have a look again

**Comment by armandino** [comment]
@kateabr thanks for updating the sample. It made it much easier to see what's going on. I just merged a PR  (#1160) that should fix this issue. Could you please try `5.0.2-SNAPSHOT` to verify? You might need to add the snapshot repository:

```xml
<repositories>
    <repository>
        <id>oss-snapshot-repository</id>
        <url>https://s01.oss.sonatype.org/content/repositories/snapshots</url>
    </repository>
</repositories>
```

**Comment by kateabr** [comment]
Works like a charm, thank you!

**Comment by armandino** [comment]
I just pushed version `5.0.2`. It should be available from Maven central shortly. Let me know if you run into any other issues.
