### ISSUE TITLE
Introduce meta annotation for `@ExtendWith(InstancioExtension.class)`

### ISSUE THREAD

**Issue by Saljack** [instancio/instancio#1216]
### Feature description
JUnit 5 supports meta annotations and it would be really nice to have a meta annotation for `@ExtendWith(InstancioExtension.class)` e.g. `@InstancioTest`.
So it allows to rewrite:
```java
@ExtendWith(InstancioExtension.class)
class SomeTest {
  // ...
}
```
to
```java
@InstancioTest
class SomeTest {
  // ...
}
```

**Comment by armandino** [comment]
@Saljack thank you for the suggestion.

Since most users are familiar with `@ExtendWith`, I'd rather avoid introducing a custom annotation. Another reason is that it makes it easier to combine multiple extensions, e.g.:

```java
@ExtendWith({InstancioExtension.class, MockitoExtension.class})
```

For these reasons, I think I'd prefer to leave defining custom annotations to users, at least for now :)

**Comment by Saljack** [comment]
@armandino 
My idea behind is that you can add some attributes on this annotation e.g. `seed` and then just write:
`@InstancioTest(seed=1234)`

**Comment by armandino** [comment]
@Saljack thanks for the follow up. Instancio supports specifying seeds at method level using the `@Seed` annotation. Please see https://www.instancio.org/user-guide/#seed-lifecycle-in-a-junit-jupiter-test for details.

**Comment by Saljack** [comment]
@armandino I know `@Seed` annotation it would be just a shorthand. Mockito has a similar annotation `@MockitoSettings(strictness=Strictness.LENIENT)`.
