### ISSUE TITLE
Improvement, use typed accessors instead of field names

### ISSUE THREAD

**Issue by gervaisb** [instancio/instancio#321]
**This is not a bug, but a wish.**

Instead of relying on field names, do you think it would be possible to use method references ?

```
// Actual
Instancio.of(Person.class)
    .generate(field("dateOfBirth"), gen -> gen.temporal().localDate().past())
    .generate(field(Phone.class, "areaCode"), gen -> gen.oneOf("604", "778"))

// Wished
Instancio.of(Person.class)
    .generate(field(Person::getDateOfBirth), gen -> gen.temporal().localDate().past())
    .generate(field(Phone.class, Phone::getAreaCode"), gen -> gen.oneOf("604", "778"))
```

**Comment by armandino** [comment]
Thank you for the suggestion. I agree it would be great to support method references. Since a method reference is just a lambda, it does not expose any information about the `Method` itself. However I think there should be some workarounds to get that information. I will need to experiment a little to see what I can do.

**Comment by armandino** [comment]
@gervaisb support for method references will be available in the next release `2.3.0`. I added some details on how it will work in #325.

**Comment by armandino** [comment]
@gervaisb latest release should be available now from Maven central. Please note that I marked the new API as experimental while I collect more feedback on how well the implementation works in practice.

**Comment by armandino** [comment]
Closing as resolved.
