### ISSUE TITLE
generate email addresses

### ISSUE THREAD

**Issue by leassis** [instancio/instancio#356]
### Feature description
We can generate dozens data types, but emails is still not possible

**Comment by armandino** [comment]
@leassis, thanks for giving the library a try. Haven you considered using a custom generator to generate emails?

```java
Generator<String> emailGenerator = random -> String.format("%s@example.com", random.lowerCaseAlphabetic(10));

Person person = Instancio.of(Person.class)
        .supply(field(Person::getEmail), emailGenerator)
        .create();
````

Let me know if this solves your use case.

In general, Instancio doesn't support generating realistic test data out of the box. Instead it supports custom generators that can be reused within a project. This is because there are already some great faker libraries out there, for example:

- https://github.com/datafaker-net/datafaker
- https://github.com/nomemory/mockneat
