### ISSUE TITLE
Difference between records and classes

### ISSUE THREAD

**Issue by psujewski** [instancio/instancio#384]
Hi!

I'm using instancio version 2.6.0 with java 17, and experiencing differences between records and classes when there is an exception in the constructor.

1. Classes

I have an immutable class as follows:

```java
final class Clazz {
    private final String property1;

    Clazz(final String property1) {
        if (property1 == null) {
            throw new RuntimeException("Should not be null");
        }
        this.property1 = property1;
    }

    public String property1() {
        return property1;
    }
}
```

And following test that passes:

```java

    @Test
    void passes_and_parameter_is_null() {
        var cr = Instancio.of(Clazz.class)
                .ignore(field(Clazz::property1))
                .create();

        assertThat(cr).isNotNull();// passes. I understand that values are passed directly to the fields.
        assertThat(cr.property1()).isNull();
    }

```

2. Records

Next, I have a record with the same logic:

```java
record Recordz(String property1) {
    Recordz {
        if (property1 == null) {
            throw new RuntimeException("Should not be null");
        }
    }
}
```

The same test fails, but not with exception:

```java

    @Test
    void fails_because_instance_is_null() {
        var result = Instancio.of(Recordz.class)
                .ignore(field(Recordz::property1))
                .create();

        assertThat(result).isNotNull();// fails, instance is null, without any exception
        assertThat(result.property1()).isNull();
    }

```

**Comment by armandino** [comment]
@psujewski, thanks for raising a bug. This actually works as expected. I can provide some background on this.

in general, Instancio tries to instantiate classes using the default, no-argument constructor. If it's not available like in the example above, it tries to instantiate the class without calling any constructors (using [Objenesis](http://www.objenesis.org)). Since no constructor is called, we don't get the exception when generating an instance of the class.

In case of records, Instancio uses the canonical constructor to create an instance. This is because fields of a `record` cannot
be set directly via reflection (at least, as far as I know). Since `field(Recordz::property1)` is ignored, a null is passed to the constructor, which then throws the exception.

This is briefly documented in the [javadoc](https://javadoc.io/doc/org.instancio/instancio-core/latest/org/instancio/InstancioApi.html#ignore(org.instancio.TargetSelector)). I'll make a note to update the docs with more details.

Are you trying to instantiate a record in an invalid state?

**Comment by psujewski** [comment]
> @psujewski, thanks for raising a bug. This actually works as expected. I can provide some background on this.
> 

@armandino, thank you for the detailed and clear answer. So the issue can be rejected.

> 
> This is briefly documented in the [javadoc](https://javadoc.io/doc/org.instancio/instancio-core/latest/org/instancio/InstancioApi.html#ignore(org.instancio.TargetSelector)). I'll make a note to update the docs with more details.
> 

I will be grateful :)

> Are you trying to instantiate a record in an invalid state?

Oh, I came across it by accident. In my use case, I changed the code that used the external popular validator:

```java
record Command(@NotNull String value/* , ...*/) {}
```
```java
class BusinessCode {
    void processLogic(@Valid Command vo) {
        // ...
    };
}
```

to simpler and no dependency:

```java
record Command(String value/* , ...*/) {
    Command {
        // programmatic validations
    }
}
```
```java
class BusinessCode {
    void processLogic(Command vo) {
        // ...
    };
}
```

The tests verified the scenarios with all the logic, including the validity of the data, and began to behave weirder than I expected. 
But its ok. I simplified and separate the tesys.

**Comment by armandino** [comment]
@psujewski thank you for providing additional context. I'm always interested in learning how the API is used in order to find areas for improvement :)

I'll keep this ticket open as a reminder to update the docs:

- https://www.instancio.org/user-guide/#ignoring-fields-or-classes

**Comment by armandino** [comment]
@psujewski documentation has been updated.
