### ISSUE TITLE
Should `instancio-processor` be removed?

### ISSUE THREAD

**Issue by armandino** [instancio/instancio#563]
The `instancio-processor` module provides support for generating metamodels. The metamodel allows referencing fields using metamodel selectors, instead of field names:

```java
Person person = Instancio.of(Person.class)
    .ignore(Person_.id)
    .generate(Person_.dateOfBirth, gen -> gen.temporal().localDate().past())
    .generate(Phone_.countryCode, gen -> gen.oneOf("+34", "+351", "+39"))
    .create();
```

However, now Instancio also supports method reference selectors, which allows the above to be specified as:

```java
Person person = Instancio.of(Person.class)
    .ignore(field(Person::getid))
    .generate(field(Person.getDateOfBirth), gen -> gen.temporal().localDate().past())
    .generate(field(Phone.getCountryCode), gen -> gen.oneOf("+34", "+351", "+39"))
    .create();
```

This raises the question whether the metamodel feature is now redundant and should be deprecated.

**Comment by EvaristeGalois11** [comment]
Just to give my two cents, the method reference selectors are much better than the metamodel. They are more easily usable without having to plug a specific annotation processor and offer basically the same benefits.

I don't know if the metamodel could be recycled in the future for much more complex tasks, but for now I agree that it feels quite redundant.

**Comment by armandino** [comment]
### Potential metamodel enhancements

#### Option A: provide convenience methods for creating objects

<table>
<tr>
<th>Regular API</th>
<th>Metamodel API</th>
</tr>
<tr>
  <td>

```java
Person person = Instancio.create(Person.class);
```

  </td>
  <td>

```java

Person person = Person_.create();

```

  </td>
</tr>


<tr>
  <td>

```java
List<Person> persons = Instancio.ofList(Person.class)
    .size(10)
    .create();
```

  </td>
  <td>

```java

List<Person> persons = Person_.list(10);

```

  </td>
</tr>


<tr>
  <td>

```java
Person person = Instancio.of(Person.class)
    .ignore(field(Person::getId))
    .create();
```

  </td>
  <td>

```java
Person person = Person_.builder()
    .ignore(Person_.id)
    .create();
```

  </td>
</tr>

</table>


#### Option B: provide a builder with `set() / supply() / generate()` methods for each field

This would reduce the need for using selectors and make object customisation more concise, e.g.:

```java
// metamodel API
Person person = Person_.builder()
    .ignoreId()
    .generateAge(gen -> gen.ints().range(20, 100))
    .create();

// vs regular API
Person person = Instancio.of(Person.class)
    .ignore(field(Person::getId))
    .generate(field(Person::getAge), gen -> gen.ints().range(20, 30))
    .create();
```

Regular API methods that accept selectors as arguments, e.g. `set(TargetSelector, Object)` could also be exposed via the builder to allow customising properties of nested objects or using other types of selectors.

------

Not sure if this has enough value to save the annotation processor from deprecation. There might be other ideas worth exploring.

**Comment by EvaristeGalois11** [comment]
Just my 2 cents again (I'll be rich in no time!):

- Option A seems kinda pointless, I think it's just confusing to provide two different syntax for doing the same thing without any real difference. For my personal taste the Regular syntax is even more clear.
- Option B could be interesting, but my fear is that it could end up being extremely difficult to maintain without many users that care about it. My previous point still stands though: is it worth it to provide two different syntax for the same thing? I'd argue that a simple library like Instancio should strive to be as simple as possible. The getter accessors are already quite pleasant to use, do we really need all the extra complexity? For example Assertj has a similar processor and it's basically abandoned now, probably because it wasn't worth it in the long run https://github.com/assertj/assertj-assertions-generator-maven-plugin

I think that what could save the processor from being deprecated is finding something that only with an annotation processor is possible. I have no idea what that could be though :D.

**Comment by armandino** [comment]
@EvaristeGalois11 Interestingly, I came across the AssertJ Maven plugin in the past but never got around to trying it :)

Regarding the annotation processor, I think you made a fair assessment. Both options are merely syntactic sugar over the main API. Having to modify build configuration to enable the annotation processor in order to use these features takes some of the convenience out of it. Overall, the processor module would need to offer something more of value to justify its existence, so it probably makes sense to deprecate it. I can't think of more useful use cases at this time either.
