### ISSUE TITLE
Exclude setter methods based on method modifiers

### ISSUE THREAD

**Issue by mnbattaglia** [instancio/instancio#618]
### Feature description

Ideally, there should be a way to select a field by its method attributes. 
The specific use case is: we need to ignore generation for private/protected accessor of setter method of a field

**Comment by armandino** [comment]
@mnbattaglia thank you for the suggestion. I'm trying to picture what such an API might look like and how it would work. Can you provide some specific examples?

**Comment by mnbattaglia** [comment]
Let's think you have a class with a protected attribute that is set by doing some calculation on public methods.
When mocking this class, the protected attribute gets a value generated and it shouldn't. So, I'm trying to exclude that field. I can use a selector for that and select that specific field and that's it, but I'm building a common library that I'll use to mock tons of different entities like this one. So, the global rule would be: exclude the attribute by its access modifier. The think is, I can do that, but the field modifier is not what I want, as my fields are always private. What I need to check is the field METHOD (setter in this case). So, it would be good to have a selector by field method, where I have a predicate that allows to evaluate the method itself (and its modifiers). The problem is that you don't know about that method until you invoke it, so there it is built with MothodAssigner.resolveSetterMethod().

I was thinking having a selector like:

`.ignore(Select.fieldMethods(method -> !isPublic(method.getModifiers()))) // Only public fields`

Hope my example is clear.

**Comment by armandino** [comment]
@mnbattaglia thanks for the additional details. My understanding is that given the following `Pojo`, you want to ignore `bar` since it doesn't have a public setter:

```java
class Pojo {
    private String foo;
    private String bar;

    public void setFoo(String foo) { this.foo = foo; }
    private void setBar(String bar) { this.bar = bar; }
}
```

There are a couple of options to go about this.

The first can be implemented using a custom selector, similar to what you proposed, where you map the field name to the setter method:

```java
static TargetSelector fieldsWithoutPublicSetter() {
    return Select.fields(field -> {
        try {
            final String setterPrefix = "set";
            SetterMethodNameWithPrefixResolver resolver = new SetterMethodNameWithPrefixResolver(setterPrefix);
            String methodName = resolver.resolveFor(field);
            Method writeMethod = field.getDeclaringClass().getDeclaredMethod(methodName, field.getType());
            return !Modifier.isPublic(writeMethod.getModifiers());
        } catch (NoSuchMethodException ex) {
            return true; // ignore fields without a setter
        }
    });
}

// Usage
Pojo pojo = Instancio.of(Pojo.class)
        .ignore(fieldsWithoutPublicSetter())
        .create();

assertThat(pojo.foo).isNotNull();
assertThat(pojo.bar).isNull();
```

Please note that `SetterMethodNameWithPrefixResolver` is Instancio's internal (package private) class, but you can easily extract a static util out of it (or use a 3rd party library to that end). Also, if the selector didn't match anything (i.e. all setters are public), it will trigger an "unused selector" error. Since you're building a common library where this will be a global rule, it might force you to use `lenient` mode to suppress this error, which is not ideal.

The second approach is to populate the POJO by assigning values [via setters](https://www.instancio.org/user-guide/#assignment-settings) (instead of fields):

```java
Settings settings = Settings.create()
    .set(Keys.ASSIGNMENT_TYPE, AssignmentType.METHOD)
    .set(Keys.ON_SET_METHOD_NOT_FOUND, OnSetMethodNotFound.IGNORE)
    .set(Keys.ON_SET_METHOD_ERROR, OnSetMethodError.IGNORE);

Pojo result = Instancio.of(Pojo.class)
    .withSettings(settings)
    .create();
```

Therefore, if your setters have logic in them, that logic will be executed. However, the setter will be invoked even if it's not public.

**Comment by mnbattaglia** [comment]
Thanks for the workaround!
Regarding the second approach, I'm doing that indeed, but want to exclude the call to the private setter :)

**Comment by armandino** [comment]
@mnbattaglia sounds good. I think it's worth making an enhancement to add more flexibility in this area. We could define a new setting to achieve that. I'll experiment a little to see what the new setting might look like.

**Comment by armandino** [comment]
@mnbattaglia I added a new setting exclude setters by method modifiers. Please take a look at the example in the [release notes](https://github.com/orgs/instancio/discussions/625). Let me know if you run into any issues.

**Comment by mnbattaglia** [comment]
Awesome @armandino ! Will definitely give it a try. Thanks for building such an amazing tool and also to give a solution to this so quickly.

**Comment by armandino** [comment]
@mnbattaglia you're very welcome! Thank you for the feedback. Much appreciated :)
