### ISSUE TITLE
Support for jOOQ

### ISSUE THREAD

**Issue by diversit** [instancio/instancio#622]
### Feature description

There only seems to be a way to select fields. Even when `ASSIGNMENT_TYPE` is set to `METHOD` there is no way to specify the 'write' method (setX, withX, property).

#### Use case: A POJO with setter methods with no fields (or not matching with field names)

E.g. When using JOOQ for database access, the generated `Record` classes have appropriate setter methods for each column, but do not have a matching field. The setter methods set the value in an index in the superclass.

```
    public CompanyRecord setId(Integer value) {
        set(0, value);
        return this;
    }
```

Since there is no matching 'field' in the class, it is not possible to select the appropriate setter method.
The Select.fields only allows selecting a field.

#### Proposal

Add a `Select.method` function which returns a `MethodSelector` which extends `TargetSelector`.

It's unfortunate that `TargetSelector` does not have a method to implement, which would allow to create custom `TargetSelector`s. In the current implementation all `TargetSelector` implementation are hard-wired and matched via a `selector instanceOf ...` and throwing a `Unhandled selector type` exception for unknown/custom `TargetSelector` implementations.

An alternative would be to be able to select a constructor. But this might be more complicated as then to pass generators for each constructor argument.

**Comment by armandino** [comment]
@diversit thanks for raising this issue! It's definitely an interesting use case.

I don't have experience with jOOQ, but from a cursory look at some examples of jOOQ-generated classes, the problem is that they do no have fields as you would expect in a regular POJO. For example, the following is the base class for `Record` types:

```java
abstract class AbstractRecord extends AbstractStore implements Record {
    // ...snip
    final RowImpl fields;
    final Object[] values;
    final Object[] originals;
    final BitSet changed;
    boolean fetched;
   // snip...
```

This makes populating such an object tricky because Instancio operates at field level. All selectors specified via the API are mapped either to a class or a field. As you suggested, using a constructor to populate an object might be an option. However, customising field values via selectors will not be possible since there are no fields to target.

I'll leave this issue open for now, but currently I'm out of ideas as to how this might be implemented without reworking much of the library.

**Comment by armandino** [comment]
Version `4.0.0` should support creating jOOQ records (added in #767). A sample test is available in this module:

https://github.com/instancio/instancio/tree/main/instancio-tests/instancio-jooq-tests

The sample test has additional logic of calculating column sizes to ensure generated values fit into columns.
