### ISSUE TITLE
Can't populate fields with same type as the root class

### ISSUE THREAD

**Issue by lucasfsousa** [instancio/instancio#744]
**Describe the bug**
Instancio can't populate fields with same type as the root class.

For example, given the following class:

```java
@Data
public class SomeClass {
    private SomeClass parent;
    private List<SomeClass> children;
    private List<String> stringList;
}
```

When we call:

```java
Instancio.of(SomeClass.class)
    withSettings(Settings.create().set(Keys.COLLECTION_MIN_SIZE, 2).lock())
    .create();
```

**Expected result**
I expect that all fields are populated and the lists have at least 2 items each.

**Actual result**
`parent` is null, `children` has 0 objects and `stringList` has at least 2 objects.

**Link to a minimal sample project reproducing the issue or runnable sample code**
```java
@Data
public class SomeClass {
    private SomeClass parent;
    private List<SomeClass> children;
    private List<String> stringList;
}

@Test
void shouldCorrectlyPopulateFields() {
    var obj = Instancio.of(SomeClass.class)
        .withSettings(Settings.create().set(Keys.COLLECTION_MIN_SIZE, 2).lock())
        .create();

    assertThat(obj.getParent()).isNotNull();
    assertThat(obj.getChildren().size()).isGreaterThanOrEqualTo(2);
    assertThat(obj.getStringList().size()).isGreaterThanOrEqualTo(2);
}
```

- Java version: `20.0..2`
- Instancio version: `3.2.0`

**Comment by armandino** [comment]
@lucasfsousa thanks for raising the issue and providing an example. This is actually working as expected. The result you're seeing is because `SomeClass` is referencing itself via the `parent` and `children` fields. When Instancio detects such a cycle, it sets the reference to null. For this reason, the `parent` field is null and `children` is an empty collection. This is briefly documented here: https://www.instancio.org/user-guide/#cyclic-objects

In this case, `SomeClass` looks like a node of a tree. Unfortunately there's no support for generating such data structures.
