### ISSUE TITLE
generator for regex-matching strings

### ISSUE THREAD

**Issue by adrian-herscu** [instancio/instancio#772]
### Feature description

It would be nice to have a regex-based string generator.

see: https://github.com/curious-odd-man/RgxGen/tree/master#regex-generate-matching-and-non-matching-strings

Maybe something like `text().pattern("...")`. e.g. `text().regex("...")`

**Comment by armandino** [comment]
Thank you for the suggestion.  I did consider adding support for regexes a while ago, but decided against it because it would require a dependency on an additional library. There are a few available, including the one you mentioned:

- https://github.com/mifmif/Generex
- https://github.com/curious-odd-man/RgxGen
- https://github.com/agarciadom/xeger

Since each one has its own features and limitations, I thought it would be best to leave this choice up to the user.  
This way you can simply create a custom generator using a library of your choice in a few lines of code. Here's an example using RgxGen:

```java
class RegexGenerator implements Generator<String> {
    private final String regex;

    private RegexGenerator(String regex) {
        this.regex = regex;
    }

    public static Generator<String> regex(String regex) {
        return new RegexGenerator(regex);
    }

    @Override
    public String generate(Random random) {
        return new RgxGen(regex).generate(new java.util.Random(random.getSeed()));
    }
}

// Usage:
MyClass myClass = Instancio.of(MyClass.class)
    .supply(field(MyClass::getSomeValue), RegexGenerator.regex("\\w{5,10}"))
    .create();

// Sample output: MyClass.someValue="AntQ4gK"
```
