### ISSUE TITLE
Build workflow - Sonar scans of PRs from forks affect `main` branch

### ISSUE THREAD

**Issue by armandino** [instancio/instancio#783]
Sonar analysis is not officially supported on PRs from forks, but it can be achieved with workarounds:

- https://community.sonarsource.com/t/sonar-cannot-be-run-on-pr-from-a-fork/69229
- https://community.sonarsource.com/t/how-to-use-sonarcloud-with-a-forked-repository-on-github/7363/34

This was implemented in #540. The works well, however, one of the side effects is that when the analysis is done on a PR from a fork, it affects the quality gate and test coverage of the `main` branch:

![image](https://github.com/instancio/instancio/assets/1159054/c9d95de8-ce93-4b3d-ac55-6ed90cae6819)

<br><br>
The PR results are then displayed via badges on the main page:

![image](https://github.com/instancio/instancio/assets/1159054/b458cb52-95cb-4fe8-bf74-749b09ec348c)

<br><br>
Ideally, the analysis of a PR should not affect the `main` branch.

**Comment by EvaristeGalois11** [comment]
Hi @armandino, it's been a while :)

I'm sorry to hear that sonar still gives you some troubles, my battle isn't over yet lol

I'm pretty sure that the problem is that the workflow is executed in the context of the main branch so sonar infers from the github token that the analysis must be relative to the main branch. I vaguely remember there were a workaround about uploading the pr number as an artifact to pass it to the maven goal.

I'm happy to try to take this issue, but I'll probably need some time to take up the whole workflow again because I forgot a lot of it.

**Comment by armandino** [comment]
@EvaristeGalois11 it's been a while indeed :) Hope all is well.

> I'm sorry to hear that sonar still gives you some troubles, my battle isn't over yet lol

Not at all. Having Sonar enabled for PRs has been great! Considering this isn't even officially supported, it's pretty a minor issue.
 
> I'm happy to try to take this issue, but I'll probably need some time to take up the whole workflow again because I forgot a lot of it.

Would very much appreciate your help!
