### ISSUE TITLE
Random is null in the context when created by Global.generatorContext()

### ISSUE THREAD

**Issue by CommentSectionScientist** [instancio/instancio#899]
**Describe the bug**
The Random field is null when it is created by Global.generatorContext()

**Expected result**
When no Seed is configured in the settings a random seed should be used to provide a DefaultRandom.
See Global#CONFIGURED_RANDOM 
null is used instead of using the NoArg constructor:
```java
public DefaultRandom() {
        this(Seeds.randomSeed());
    }
```

**Actual result**
Nullpointer Exception:
```
Caused by: java.lang.NullPointerException: Cannot invoke "org.instancio.Random.intRange(int, int)" because the return value of "org.instancio.generator.GeneratorContext.random()" is null
	at org.instancio.internal.generator.util.CollectionGenerator.hints(CollectionGenerator.java:139)
	at org.instancio.internal.handlers.UsingGeneratorResolverHandler.getResult(UsingGeneratorResolverHandler.java:65)
	at org.instancio.internal.GeneratorFacade.getGeneratorResult(GeneratorFacade.java:131)
	at org.instancio.internal.GeneratorFacade.generateNodeValue(GeneratorFacade.java:90)
```

**Additional information**
The Generator is created by the ServiceLoader (see https://github.com/CommentSectionScientist/InstancioGeneratorContextRandom/blob/master/src/test/java/de/ossi/generator/MyClassGenerator.java#L17)

**Link to a minimal sample project reproducing the issue or runnable sample code**
https://github.com/CommentSectionScientist/InstancioGeneratorContextRandom/blob/master/src/test/java/de/ossi/generator/ReproducerTest.java

- Java version: 17
- Instancio version: 4.1.0

**Comment by armandino** [comment]
Thanks for raising this issue and creating a sample project. It helps a lot!

Unfortunately, this usage is not supported because `CollectionGenerator` and `Global`  are internal classes. Anything under `internal` package or annotated with `@InternalApi` is not intended to be used by users.

Based on the sample project, I assume the goal is to generate a collection of size 1 (by default) for `MyClass.values`. If that's the case, you could use the provided `Generators` instance in your SPI implementation:

```java
public class MyClassGenerator implements InstancioServiceProvider {

    @Override
    public InstancioServiceProvider.GeneratorProvider getGeneratorProvider() {
        return (node, generators) -> {
            if (matchesNode(node)) {
                // 'generators' provides access to all built-in generators
                return generators.collection().size(1);
            }
            return null;
        };
    }

    private boolean matchesNode(Node node) {
        Field field = node.getField();
        return field != null
                && MyClass.class.isAssignableFrom(field.getDeclaringClass())
                && node.getTargetClass() == List.class;
    }
}
```

Does this work for you use case?

**Comment by CommentSectionScientist** [comment]
Hey,

thanks for the answer, i did not see the annotation.
Just to clarify: All custom Generators should just implement the Generator interface, correct?
(My code provided is not a real Generator since it just delegates, so it shouldnt implement the interface)

**Comment by armandino** [comment]
> All custom Generators should just implement the Generator interface, correct?

That's right, all generators should implement the `Generator` interface. The `Global` class contains an internal instance of `Random` and `Settings`. Since you already get those objects using public APIs, the `Global` class shouldn't be needed for a custom generator. To delegate to the collection generator, you can use the `collection()` method as above.

**Comment by CommentSectionScientist** [comment]
Ok thanks.
The suggested solutions works with version 4.1.0
(i got some exception when using 3.6.0 in our main project, so I just bumped up the version)

**Comment by armandino** [comment]
> i got some exception when using 3.6.0 in our main project, so I just bumped up the version

Thanks for the update. This makes sense now. There was a fix for this bug not too long ago:

- #882

Let me know if you run into other issues.
