### ISSUE TITLE
Instancio sometimes fills a field (child node) of a type even though that type has a custom generator

### ISSUE THREAD

**Issue by CommentSectionScientist** [instancio/instancio#907]
**Describe the bug**
I got a weird bug, that Instancio sometimes (~ 8-10% of cases) tries to fill a field of a node that has a Custom Generator.
![grafik](https://github.com/instancio/instancio/assets/36775764/8a2cf397-6f21-43cb-ac72-b67d30c1ac76)
When debugging MyEnumGenerator#getGeneratorProvider (see reproducer link) you can see, that only sometimes the depth is 2.

**Expected result**
If a type has a Generator Instancio shouldnt fill fields of that type.

**Actual result**
Instancio sporadically fills the fields of the type with the custom generator.

**Additional information**
If I just try to create an instance of MyEnum (see reproducer link) it works as expected and the int field is never changed. 

**Link to a minimal sample project reproducing the issue or runnable sample code**
https://github.com/CommentSectionScientist/InstancioGeneratorContextRandom/blob/ChildNodes/src/test/java/de/ossi/generator/ReproducerTest.java

- Java version: 17
- Instancio version: 4.1.0

**Comment by armandino** [comment]
@CommentSectionScientist thanks for the sample. I see what's going on here.

I'll paste the sample code here for future reference:

```java
public class MyEnum implements IEnum {
    public static final MyEnum ENUM_0 = new MyEnum(0);
    public static final MyEnum ENUM_1 = new MyEnum(1);
    public static final MyEnum ENUM_2 = new MyEnum(2);

    private final int ordinal;

    public MyEnum(int ordinal) {this.ordinal = ordinal;}

    public int ordinal() {
        return ordinal;
    }
}

class MyEnumGenerator implements Generator<MyEnum> {
    @Override
    public MyEnum generate(Random random) {
        int randomOrdinal = random.intRange(0, 10);
        return new MyEnum(randomOrdinal);
    }
}
```

The issue only happens when `MyEnum` with `ordinal = 0` is generated. This is because the default `AfterGenerate` hint is `POPULATE_NULLS_AND_DEFAULT_PRIMITIVES`. As a result, if a custom generator returns an object with `null` fields and default primitive values (e.g. `0` for `int`), Instancio will populate those fields with random values. The assumption is that those fields are not initialised (see https://www.instancio.org/user-guide/#custom-generators for details).

You can fix this by changing the hint to `DO_NOT_MODIFY`. This will make generated objects read-only (even selectors won't be able to mutate `MyEnum`). Alternatively, you can use `APPLY_SELECTORS` if you want to be able to update generated instances using a selector.

Example:

```java
class MyEnumGenerator implements Generator<MyEnum> {
    @Override
    public MyEnum generate(Random random) {
        int randomOrdinal = random.intRange(0, 10);
        return new MyEnum(randomOrdinal);
    }

    @Override
    public Hints hints() {
        return Hints.afterGenerate(AfterGenerate.DO_NOT_MODIFY);
    }
}
```

**Comment by CommentSectionScientist** [comment]
Thanks for the fast reply, that works! It was driving my nuts that the behaviour was only sporadically :D
