### ISSUE TITLE
InstancioExtension: Make the log level adjustable

### ISSUE THREAD

**Issue by MatthiasOs** [instancio/instancio#947]
### InstancioExtension: Make the log level adjustable
Currently the InstancioExtension logs the seed and other information on debug log level:
https://github.com/instancio/instancio/blob/main/instancio-junit/src/main/java/org/instancio/junit/InstancioExtension.java#L115

In our CI build debug log level is omitted, only error level is displayed.
If a test which uses Instancio sporadically fails and the seed isn't displayed we are unable to reproduce the error with the exact data generated by Instancio.
It would be nice to be able to adjust the log level used by the InstancioExtension.

**Comment by armandino** [comment]
I'm not sure if it makes sense to add a custom setting to the library since logging frameworks support adjusting the log level. Have you considered updating the configuration in your test module? For example, if you use logback, you should be able to set:

```xml
<logger name="org.instancio.junit.InstancioExtension" level="debug"/>
```

**Comment by MatthiasOs** [comment]
You are right, adjusting logger works for my usecase.
Thanks.

**Comment by armandino** [comment]
@MatthiasOs after giving it some more thought, it's probably best to log the failed seed at ERROR level instead of DEBUG. Not sure why I chose debug initially, but it seems like the wrong choice in hindsight since we want to maximise the visibility of this message.

This should make the seed show up in your CI logs without changing logging configuration.
